-- Execute este SQL no Supabase SQL Editor para preparar a base do ObraBoard.
--
-- Este script e idempotente: pode ser executado novamente sem apagar dados.
-- Ele cria as tabelas que nao existirem, adiciona as colunas usadas pelo app,
-- recria indices e libera as policies publicas usadas no prototipo atual.
-- Quando houver login real, troque estas policies por regras por usuario/obra/perfil.

-- Preflight para bancos antigos que ja possuem algumas tabelas sem as colunas
-- novas. Execute junto com o script completo; esta parte evita erros em indices
-- e constraints criados mais abaixo.
alter table if exists public.mao_obra
add column if not exists atividade_id bigint,
add column if not exists obra_id bigint,
add column if not exists turno_id bigint,
add column if not exists funcao text,
add column if not exists quantidade numeric default 0,
add column if not exists turno text,
add column if not exists data_turno date;

alter table if exists public.atividade_recursos
add column if not exists atividade_id bigint,
add column if not exists funcao text,
add column if not exists quantidade_prevista numeric default 0;

alter table if exists public.atividades
add column if not exists turno_id bigint,
add column if not exists obra_id bigint,
add column if not exists tempo_previsto_horas numeric default 0,
add column if not exists origem_atividade_id bigint,
add column if not exists data_turno date;

create table if not exists public.atividades (
  id bigint generated by default as identity primary key,
  obra_id bigint,
  prioridade text not null default 'C',
  disciplina text not null default '',
  atividade text not null default '',
  local text not null default '',
  responsavel text not null default '',
  previsto numeric not null default 0,
  realizado numeric default 0,
  unidade text default 'un',
  tempo_previsto_horas numeric default 0,
  origem_atividade_id bigint,
  turno_id bigint,
  status text not null default 'Planejada',
  progresso numeric default 0,
  turno text,
  data_turno date,
  created_at timestamptz not null default now()
);

alter table public.atividades
add column if not exists obra_id bigint,
add column if not exists prioridade text not null default 'C',
add column if not exists disciplina text not null default '',
add column if not exists atividade text not null default '',
add column if not exists local text not null default '',
add column if not exists responsavel text not null default '',
add column if not exists previsto numeric not null default 0,
add column if not exists realizado numeric default 0,
add column if not exists unidade text default 'un',
add column if not exists tempo_previsto_horas numeric default 0,
add column if not exists origem_atividade_id bigint,
add column if not exists turno_id bigint,
add column if not exists status text not null default 'Planejada',
add column if not exists progresso numeric default 0,
add column if not exists turno text,
add column if not exists data_turno date,
add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'atividades_origem_atividade_id_fkey'
      and conrelid = 'public.atividades'::regclass
  ) then
    alter table public.atividades
    add constraint atividades_origem_atividade_id_fkey
    foreign key (origem_atividade_id)
    references public.atividades(id)
    on delete set null;
  end if;
end $$;

create table if not exists public.mao_obra (
  id bigint generated by default as identity primary key,
  obra_id bigint,
  turno_id bigint,
  atividade_id bigint,
  funcao text,
  quantidade numeric default 0,
  turno text,
  data_turno date,
  created_at timestamptz not null default now()
);

alter table public.mao_obra
add column if not exists obra_id bigint,
add column if not exists turno_id bigint,
add column if not exists atividade_id bigint,
add column if not exists funcao text,
add column if not exists quantidade numeric default 0,
add column if not exists turno text,
add column if not exists data_turno date,
add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'mao_obra_atividade_id_fkey'
      and conrelid = 'public.mao_obra'::regclass
  ) then
    alter table public.mao_obra
    add constraint mao_obra_atividade_id_fkey
    foreign key (atividade_id)
    references public.atividades(id)
    on delete set null;
  end if;
end $$;

create table if not exists public.atividade_recursos (
  id bigint generated by default as identity primary key,
  atividade_id bigint not null references public.atividades(id) on delete cascade,
  funcao text not null,
  quantidade_prevista numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.atividade_recursos
add column if not exists atividade_id bigint,
add column if not exists funcao text not null default '',
add column if not exists quantidade_prevista numeric not null default 0,
add column if not exists created_at timestamptz not null default now();

create table if not exists public.recursos_disponiveis (
  id bigint generated by default as identity primary key,
  obra_id bigint,
  turno_id bigint,
  data_turno date not null,
  turno text not null,
  funcao text not null,
  quantidade numeric not null default 0,
  carga_horaria numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.recursos_disponiveis
add column if not exists obra_id bigint,
add column if not exists turno_id bigint,
add column if not exists data_turno date,
add column if not exists turno text,
add column if not exists funcao text,
add column if not exists quantidade numeric not null default 0,
add column if not exists carga_horaria numeric not null default 0,
add column if not exists created_at timestamptz not null default now();

create table if not exists public.cadastro_base (
  id text primary key,
  dados jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.cadastro_base
add column if not exists dados jsonb not null default '{}'::jsonb,
add column if not exists updated_at timestamptz not null default now();

create index if not exists atividades_obra_turno_idx
on public.atividades (obra_id, turno_id, data_turno, turno);

create index if not exists atividades_origem_atividade_id_idx
on public.atividades (origem_atividade_id);

create index if not exists mao_obra_atividade_id_idx
on public.mao_obra (atividade_id);

create index if not exists mao_obra_obra_turno_idx
on public.mao_obra (obra_id, turno_id, data_turno, turno);

create index if not exists atividade_recursos_atividade_id_idx
on public.atividade_recursos (atividade_id);

create index if not exists recursos_disponiveis_obra_turno_idx
on public.recursos_disponiveis (obra_id, turno_id, data_turno, turno);

alter table public.atividades enable row level security;
alter table public.atividade_recursos enable row level security;
alter table public.recursos_disponiveis enable row level security;
alter table public.cadastro_base enable row level security;
alter table public.mao_obra enable row level security;

drop policy if exists "Permitir leitura publica de atividades" on public.atividades;
drop policy if exists "Permitir criacao publica de atividades" on public.atividades;
drop policy if exists "Permitir edicao publica de atividades" on public.atividades;
drop policy if exists "Permitir exclusao publica de atividades" on public.atividades;
drop policy if exists "Permitir leitura publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir criacao publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir edicao publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir exclusao publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir leitura publica de recursos disponiveis" on public.recursos_disponiveis;
drop policy if exists "Permitir criacao publica de recursos disponiveis" on public.recursos_disponiveis;
drop policy if exists "Permitir edicao publica de recursos disponiveis" on public.recursos_disponiveis;
drop policy if exists "Permitir exclusao publica de recursos disponiveis" on public.recursos_disponiveis;
drop policy if exists "Permitir leitura publica de cadastro base" on public.cadastro_base;
drop policy if exists "Permitir criacao publica de cadastro base" on public.cadastro_base;
drop policy if exists "Permitir edicao publica de cadastro base" on public.cadastro_base;
drop policy if exists "Permitir leitura publica de mao de obra" on public.mao_obra;
drop policy if exists "Permitir criacao publica de mao de obra" on public.mao_obra;
drop policy if exists "Permitir edicao publica de mao de obra" on public.mao_obra;
drop policy if exists "Permitir exclusao publica de mao de obra" on public.mao_obra;

create policy "Permitir leitura publica de atividades"
on public.atividades for select to anon using (true);

create policy "Permitir criacao publica de atividades"
on public.atividades for insert to anon with check (true);

create policy "Permitir edicao publica de atividades"
on public.atividades for update to anon using (true) with check (true);

create policy "Permitir exclusao publica de atividades"
on public.atividades for delete to anon using (true);

create policy "Permitir leitura publica de recursos de atividades"
on public.atividade_recursos for select to anon using (true);

create policy "Permitir criacao publica de recursos de atividades"
on public.atividade_recursos for insert to anon with check (true);

create policy "Permitir edicao publica de recursos de atividades"
on public.atividade_recursos for update to anon using (true) with check (true);

create policy "Permitir exclusao publica de recursos de atividades"
on public.atividade_recursos for delete to anon using (true);

create policy "Permitir leitura publica de recursos disponiveis"
on public.recursos_disponiveis for select to anon using (true);

create policy "Permitir criacao publica de recursos disponiveis"
on public.recursos_disponiveis for insert to anon with check (true);

create policy "Permitir edicao publica de recursos disponiveis"
on public.recursos_disponiveis for update to anon using (true) with check (true);

create policy "Permitir exclusao publica de recursos disponiveis"
on public.recursos_disponiveis for delete to anon using (true);

create policy "Permitir leitura publica de cadastro base"
on public.cadastro_base for select to anon using (true);

create policy "Permitir criacao publica de cadastro base"
on public.cadastro_base for insert to anon with check (true);

create policy "Permitir edicao publica de cadastro base"
on public.cadastro_base for update to anon using (true) with check (true);

create policy "Permitir leitura publica de mao de obra"
on public.mao_obra for select to anon using (true);

create policy "Permitir criacao publica de mao de obra"
on public.mao_obra for insert to anon with check (true);

create policy "Permitir edicao publica de mao de obra"
on public.mao_obra for update to anon using (true) with check (true);

create policy "Permitir exclusao publica de mao de obra"
on public.mao_obra for delete to anon using (true);
