-- Execute este SQL no Supabase SQL Editor para preparar a base do OpsBoard.
--
-- Observacao: isto e adequado para o prototipo atual. Quando houver login real,
-- troque estas politicas por regras vinculadas ao usuario/obra/perfil.

alter table public.atividades
add column if not exists obra_id bigint,
add column if not exists tempo_previsto_horas numeric default 0,
add column if not exists origem_atividade_id bigint references public.atividades(id) on delete set null;

alter table public.mao_obra
add column if not exists atividade_id bigint references public.atividades(id) on delete set null,
add column if not exists obra_id bigint;

create index if not exists mao_obra_atividade_id_idx
on public.mao_obra (atividade_id);

create index if not exists mao_obra_obra_turno_idx
on public.mao_obra (obra_id, data_turno, turno);

create index if not exists atividades_obra_turno_idx
on public.atividades (obra_id, data_turno, turno);

create table if not exists public.atividade_recursos (
  id bigint generated by default as identity primary key,
  atividade_id bigint not null references public.atividades(id) on delete cascade,
  funcao text not null,
  quantidade_prevista numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists atividade_recursos_atividade_id_idx
on public.atividade_recursos (atividade_id);

alter table public.atividades enable row level security;
alter table public.atividade_recursos enable row level security;
alter table public.mao_obra enable row level security;

drop policy if exists "Permitir leitura publica de atividades" on public.atividades;
drop policy if exists "Permitir criacao publica de atividades" on public.atividades;
drop policy if exists "Permitir edicao publica de atividades" on public.atividades;
drop policy if exists "Permitir exclusao publica de atividades" on public.atividades;
drop policy if exists "Permitir leitura publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir criacao publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir edicao publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir exclusao publica de recursos de atividades" on public.atividade_recursos;
drop policy if exists "Permitir leitura publica de mao de obra" on public.mao_obra;
drop policy if exists "Permitir criacao publica de mao de obra" on public.mao_obra;
drop policy if exists "Permitir edicao publica de mao de obra" on public.mao_obra;
drop policy if exists "Permitir exclusao publica de mao de obra" on public.mao_obra;

create policy "Permitir leitura publica de atividades"
on public.atividades
for select
to anon
using (true);

create policy "Permitir criacao publica de atividades"
on public.atividades
for insert
to anon
with check (true);

create policy "Permitir edicao publica de atividades"
on public.atividades
for update
to anon
using (true)
with check (true);

create policy "Permitir exclusao publica de atividades"
on public.atividades
for delete
to anon
using (true);

create policy "Permitir leitura publica de recursos de atividades"
on public.atividade_recursos
for select
to anon
using (true);

create policy "Permitir criacao publica de recursos de atividades"
on public.atividade_recursos
for insert
to anon
with check (true);

create policy "Permitir edicao publica de recursos de atividades"
on public.atividade_recursos
for update
to anon
using (true)
with check (true);

create policy "Permitir exclusao publica de recursos de atividades"
on public.atividade_recursos
for delete
to anon
using (true);

create policy "Permitir leitura publica de mao de obra"
on public.mao_obra
for select
to anon
using (true);

create policy "Permitir criacao publica de mao de obra"
on public.mao_obra
for insert
to anon
with check (true);

create policy "Permitir edicao publica de mao de obra"
on public.mao_obra
for update
to anon
using (true)
with check (true);

create policy "Permitir exclusao publica de mao de obra"
on public.mao_obra
for delete
to anon
using (true);
