-- Migração SaaS do ObraBoard.
-- Execute no Supabase SQL Editor depois de revisar as policies para o seu modelo de convites.
-- A aplicação deixa de usar localStorage operacional; estas tabelas passam a ser a fonte oficial.

create extension if not exists pgcrypto;

create table if not exists public.empresas (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.empresa_usuarios (
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  papel text not null default 'usuario',
  created_at timestamptz not null default now(),
  primary key (empresa_id, user_id)
);

create or replace function public.usuario_empresa_ids()
returns setof uuid
language sql
security definer
stable
set search_path = public
as $$
  select empresa_id
  from public.empresa_usuarios
  where user_id = auth.uid()
$$;

create table if not exists public.obras (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nome text not null,
  codigo text default '',
  cliente text default '',
  contrato text default '',
  inicio date,
  termino date,
  orcamento text default '',
  situacao text default 'Planejamento',
  criticidade text default 'Baixa',
  escopo text default '',
  observacoes text default '',
  logo_url text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.turnos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  obra_id bigint references public.obras(id) on delete cascade,
  nome text not null,
  hora_inicio text default '',
  hora_fim text default '',
  desconta_refeicao boolean not null default false,
  horas_trabalho numeric not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.usuarios_operacionais (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  obra_id bigint references public.obras(id) on delete cascade,
  nome text not null,
  funcao text default '',
  email text default '',
  nivel_acesso text default 'Usuario',
  created_at timestamptz not null default now()
);

create table if not exists public.disciplinas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  obra_id bigint references public.obras(id) on delete cascade,
  codigo text default '',
  nome text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.funcoes_previstas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  obra_id bigint references public.obras(id) on delete cascade,
  nome text not null,
  quantidade numeric not null default 0,
  carga_horaria numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.atividades
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists iniciado_em timestamptz,
add column if not exists pausado_em timestamptz,
add column if not exists finalizado_em timestamptz,
add column if not exists tempo_acumulado_ms bigint not null default 0,
add column if not exists updated_at timestamptz not null default now();

alter table public.mao_obra
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade;

alter table public.atividade_recursos
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade;

alter table public.recursos_disponiveis
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade;

create table if not exists public.restricoes_historico (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid references public.empresas(id) on delete cascade,
  atividade_id bigint not null references public.atividades(id) on delete cascade,
  obra_id bigint,
  turno_id bigint,
  data_turno date,
  turno text,
  atividade text not null default '',
  responsavel text not null default '',
  texto text not null default '',
  status text not null default 'aberta',
  registrada_em timestamptz not null default now(),
  parada_em timestamptz,
  retomada_em timestamptz,
  encerrada_em timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.turnos_operacao (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid references public.empresas(id) on delete cascade,
  obra_id bigint not null,
  turno_id bigint,
  data_turno date not null,
  turno text not null,
  status text not null default 'planejado',
  publicado_em timestamptz,
  iniciado_em timestamptz,
  pausado_em timestamptz,
  encerrado_em timestamptz,
  rdo_gerado_em timestamptz,
  tempo_acumulado_ms bigint not null default 0,
  running_since timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint turnos_operacao_unico unique (obra_id, data_turno, turno)
);

create table if not exists public.checkout_validacoes (
  atividade_id bigint primary key references public.atividades(id) on delete cascade,
  empresa_id uuid references public.empresas(id) on delete cascade,
  obra_id bigint,
  turno_id bigint,
  data_turno date,
  turno text,
  validado_em timestamptz not null default now()
);

-- Reparo idempotente para bancos onde uma tentativa anterior criou tabelas
-- antes de todas as colunas SaaS existirem. create table if not exists nao
-- altera tabelas existentes, entao completamos as colunas antes dos indices/RLS.
alter table if exists public.obras
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists nome text not null default '',
add column if not exists codigo text default '',
add column if not exists cliente text default '',
add column if not exists contrato text default '',
add column if not exists inicio date,
add column if not exists termino date,
add column if not exists orcamento text default '',
add column if not exists situacao text default 'Planejamento',
add column if not exists criticidade text default 'Baixa',
add column if not exists escopo text default '',
add column if not exists observacoes text default '',
add column if not exists logo_url text default '',
add column if not exists created_at timestamptz not null default now();

alter table if exists public.turnos
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists obra_id bigint references public.obras(id) on delete cascade,
add column if not exists nome text not null default '',
add column if not exists hora_inicio text default '',
add column if not exists hora_fim text default '',
add column if not exists desconta_refeicao boolean not null default false,
add column if not exists horas_trabalho numeric not null default 0,
add column if not exists ativo boolean not null default true,
add column if not exists created_at timestamptz not null default now();

alter table if exists public.usuarios_operacionais
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists obra_id bigint references public.obras(id) on delete cascade,
add column if not exists nome text not null default '',
add column if not exists funcao text default '',
add column if not exists email text default '',
add column if not exists nivel_acesso text default 'Usuario',
add column if not exists created_at timestamptz not null default now();

alter table if exists public.disciplinas
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists obra_id bigint references public.obras(id) on delete cascade,
add column if not exists codigo text default '',
add column if not exists nome text not null default '',
add column if not exists created_at timestamptz not null default now();

alter table if exists public.funcoes_previstas
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists obra_id bigint references public.obras(id) on delete cascade,
add column if not exists nome text not null default '',
add column if not exists quantidade numeric not null default 0,
add column if not exists carga_horaria numeric not null default 0,
add column if not exists created_at timestamptz not null default now();

alter table if exists public.restricoes_historico
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists atividade_id bigint references public.atividades(id) on delete cascade,
add column if not exists obra_id bigint,
add column if not exists turno_id bigint,
add column if not exists data_turno date,
add column if not exists turno text,
add column if not exists atividade text not null default '',
add column if not exists responsavel text not null default '',
add column if not exists texto text not null default '',
add column if not exists status text not null default 'aberta',
add column if not exists registrada_em timestamptz not null default now(),
add column if not exists parada_em timestamptz,
add column if not exists retomada_em timestamptz,
add column if not exists encerrada_em timestamptz,
add column if not exists created_at timestamptz not null default now();

alter table if exists public.turnos_operacao
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists obra_id bigint,
add column if not exists turno_id bigint,
add column if not exists data_turno date,
add column if not exists turno text,
add column if not exists status text not null default 'planejado',
add column if not exists publicado_em timestamptz,
add column if not exists iniciado_em timestamptz,
add column if not exists pausado_em timestamptz,
add column if not exists encerrado_em timestamptz,
add column if not exists rdo_gerado_em timestamptz,
add column if not exists tempo_acumulado_ms bigint not null default 0,
add column if not exists running_since timestamptz,
add column if not exists updated_at timestamptz not null default now(),
add column if not exists created_at timestamptz not null default now();

alter table if exists public.checkout_validacoes
add column if not exists empresa_id uuid references public.empresas(id) on delete cascade,
add column if not exists obra_id bigint,
add column if not exists turno_id bigint,
add column if not exists data_turno date,
add column if not exists turno text,
add column if not exists validado_em timestamptz not null default now();

create index if not exists atividades_empresa_idx on public.atividades (empresa_id);
create index if not exists restricoes_empresa_turno_idx on public.restricoes_historico (empresa_id, obra_id, turno_id, data_turno);
create index if not exists turnos_operacao_empresa_turno_idx on public.turnos_operacao (empresa_id, obra_id, turno_id, data_turno);
create index if not exists checkout_validacoes_empresa_turno_idx on public.checkout_validacoes (empresa_id, obra_id, turno_id, data_turno);

create or replace function public.migrar_cadastro_base_para_saas(p_empresa_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dados jsonb;
  v_obra jsonb;
  v_dados_obra jsonb;
begin
  select dados into v_dados
  from public.cadastro_base
  where id = 'default';

  if v_dados is null then
    return;
  end if;

  for v_obra in select * from jsonb_array_elements(coalesce(v_dados->'obras', '[]'::jsonb))
  loop
    insert into public.obras (
      id, empresa_id, nome, codigo, cliente, contrato, inicio, termino, orcamento,
      situacao, criticidade, escopo, observacoes, logo_url
    )
    values (
      (v_obra->>'id')::bigint,
      p_empresa_id,
      coalesce(v_obra->>'nome', ''),
      coalesce(v_obra->>'codigo', ''),
      coalesce(v_obra->>'cliente', ''),
      coalesce(v_obra->>'contrato', ''),
      nullif(v_obra->>'inicio', '')::date,
      nullif(v_obra->>'termino', '')::date,
      coalesce(v_obra->>'orcamento', ''),
      coalesce(v_obra->>'situacao', 'Planejamento'),
      coalesce(v_obra->>'criticidade', 'Baixa'),
      coalesce(v_obra->>'escopo', ''),
      coalesce(v_obra->>'observacoes', ''),
      coalesce(v_obra->>'logoUrl', '')
    )
    on conflict (id) do update set
      empresa_id = excluded.empresa_id,
      nome = excluded.nome,
      codigo = excluded.codigo,
      cliente = excluded.cliente;

    v_dados_obra := coalesce(v_dados->'dadosPorObra'->(v_obra->>'id'), '{}'::jsonb);

    insert into public.turnos (id, empresa_id, obra_id, nome, hora_inicio, hora_fim, desconta_refeicao, horas_trabalho)
    select
      (item->>'id')::bigint,
      p_empresa_id,
      (v_obra->>'id')::bigint,
      coalesce(item->>'nome', ''),
      coalesce(item->>'horaInicio', ''),
      coalesce(item->>'horaFim', ''),
      coalesce((item->>'descontaRefeicao')::boolean, false),
      coalesce((item->>'horasTrabalho')::numeric, 0)
    from jsonb_array_elements(coalesce(v_dados_obra->'turnos', v_dados->'turnos', '[]'::jsonb)) item
    on conflict (id) do nothing;

    insert into public.usuarios_operacionais (id, empresa_id, obra_id, nome, funcao, email, nivel_acesso)
    select
      (item->>'id')::bigint,
      p_empresa_id,
      (v_obra->>'id')::bigint,
      coalesce(item->>'nome', ''),
      coalesce(item->>'funcao', ''),
      coalesce(item->>'email', ''),
      coalesce(item->>'nivelAcesso', 'Usuario')
    from jsonb_array_elements(coalesce(v_dados_obra->'usuarios', v_dados->'usuarios', '[]'::jsonb)) item
    on conflict (id) do nothing;
  end loop;

  update public.atividades a
  set empresa_id = p_empresa_id
  where empresa_id is null
    and exists (select 1 from public.obras o where o.id = a.obra_id and o.empresa_id = p_empresa_id);

  update public.mao_obra m
  set empresa_id = p_empresa_id
  where empresa_id is null
    and exists (select 1 from public.obras o where o.id = m.obra_id and o.empresa_id = p_empresa_id);

  update public.recursos_disponiveis r
  set empresa_id = p_empresa_id
  where empresa_id is null
    and exists (select 1 from public.obras o where o.id = r.obra_id and o.empresa_id = p_empresa_id);
end;
$$;

alter table public.empresas enable row level security;
alter table public.empresa_usuarios enable row level security;
alter table public.obras enable row level security;
alter table public.turnos enable row level security;
alter table public.usuarios_operacionais enable row level security;
alter table public.disciplinas enable row level security;
alter table public.funcoes_previstas enable row level security;
alter table public.atividades enable row level security;
alter table public.mao_obra enable row level security;
alter table public.atividade_recursos enable row level security;
alter table public.recursos_disponiveis enable row level security;
alter table public.restricoes_historico enable row level security;
alter table public.turnos_operacao enable row level security;
alter table public.checkout_validacoes enable row level security;

drop policy if exists "SaaS empresas por usuario" on public.empresas;
create policy "SaaS empresas por usuario"
on public.empresas for all to authenticated
using (id in (select public.usuario_empresa_ids()))
with check (id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS vinculos por usuario" on public.empresa_usuarios;
create policy "SaaS vinculos por usuario"
on public.empresa_usuarios for select to authenticated
using (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS obras por empresa" on public.obras;
create policy "SaaS obras por empresa"
on public.obras for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS turnos por empresa" on public.turnos;
create policy "SaaS turnos por empresa"
on public.turnos for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS usuarios operacionais por empresa" on public.usuarios_operacionais;
create policy "SaaS usuarios operacionais por empresa"
on public.usuarios_operacionais for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS disciplinas por empresa" on public.disciplinas;
create policy "SaaS disciplinas por empresa"
on public.disciplinas for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS funcoes por empresa" on public.funcoes_previstas;
create policy "SaaS funcoes por empresa"
on public.funcoes_previstas for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS atividades por empresa" on public.atividades;
create policy "SaaS atividades por empresa"
on public.atividades for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS mao obra por empresa" on public.mao_obra;
create policy "SaaS mao obra por empresa"
on public.mao_obra for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS recursos atividades por empresa" on public.atividade_recursos;
create policy "SaaS recursos atividades por empresa"
on public.atividade_recursos for all to authenticated
using (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.atividades a
    where a.id = atividade_id
      and a.empresa_id in (select public.usuario_empresa_ids())
  )
)
with check (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.atividades a
    where a.id = atividade_id
      and a.empresa_id in (select public.usuario_empresa_ids())
  )
);

drop policy if exists "SaaS recursos disponiveis por empresa" on public.recursos_disponiveis;
create policy "SaaS recursos disponiveis por empresa"
on public.recursos_disponiveis for all to authenticated
using (empresa_id in (select public.usuario_empresa_ids()))
with check (empresa_id in (select public.usuario_empresa_ids()));

drop policy if exists "SaaS restricoes por empresa" on public.restricoes_historico;
create policy "SaaS restricoes por empresa"
on public.restricoes_historico for all to authenticated
using (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.atividades a
    where a.id = atividade_id
      and a.empresa_id in (select public.usuario_empresa_ids())
  )
)
with check (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.atividades a
    where a.id = atividade_id
      and a.empresa_id in (select public.usuario_empresa_ids())
  )
);

drop policy if exists "SaaS turnos operacao por empresa" on public.turnos_operacao;
create policy "SaaS turnos operacao por empresa"
on public.turnos_operacao for all to authenticated
using (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.obras o
    where o.id = obra_id
      and o.empresa_id in (select public.usuario_empresa_ids())
  )
)
with check (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.obras o
    where o.id = obra_id
      and o.empresa_id in (select public.usuario_empresa_ids())
  )
);

drop policy if exists "SaaS validacoes checkout por empresa" on public.checkout_validacoes;
create policy "SaaS validacoes checkout por empresa"
on public.checkout_validacoes for all to authenticated
using (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.atividades a
    where a.id = atividade_id
      and a.empresa_id in (select public.usuario_empresa_ids())
  )
)
with check (
  empresa_id in (select public.usuario_empresa_ids())
  or exists (
    select 1 from public.atividades a
    where a.id = atividade_id
      and a.empresa_id in (select public.usuario_empresa_ids())
  )
);
